// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt4_Bc4YNIFeVLe9PrBemgHYWSJfNIyGk',
    appId: '1:417182149715:web:380586e450ea8ced76eaa6',
    messagingSenderId: '417182149715',
    projectId: 'my-quran-01',
    authDomain: 'my-quran-01.firebaseapp.com',
    storageBucket: 'my-quran-01.appspot.com',
    measurementId: 'G-WNCD332XQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNPxXv07T5RwEKyo_ND893L7Cksfyly_Q',
    appId: '1:417182149715:android:2c58ee52327c82a876eaa6',
    messagingSenderId: '417182149715',
    projectId: 'my-quran-01',
    storageBucket: 'my-quran-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA87wzR9SMIWff99O-mAdJCL6VDvN5hclo',
    appId: '1:417182149715:ios:f6d207c487b6110e76eaa6',
    messagingSenderId: '417182149715',
    projectId: 'my-quran-01',
    storageBucket: 'my-quran-01.appspot.com',
    androidClientId: '417182149715-4fdbf0naurtnenclm83lrsnkur9nmd7u.apps.googleusercontent.com',
    iosClientId: '417182149715-icusnhceqetnqlinprnn9o8tamct4g7q.apps.googleusercontent.com',
    iosBundleId: 'com.alee.hatimapp',
  );
}
