class HatimPage {
  const HatimPage({
    required this.id,
    required this.status,
  });

  factory HatimPage.fromJson(Map<String, dynamic> map) {
    return HatimPage(
      id: map['id'] as int,
      status: PageStatus.values.byName(map['status'] as String),
    );
  }

  final int id;
  final PageStatus status;
}

enum PageStatus { empty, process, done }

final hatimPageMockDataList = [
  hatimPageMockData1,
  hatimPageMockData2,
  hatimPageMockData3,
  hatimPageMockData4,
  hatimPageMockData5,
  hatimPageMockData6,
  hatimPageMockData7,
  hatimPageMockData8,
  hatimPageMockData9,
  hatimPageMockData10,
  hatimPageMockData11,
  hatimPageMockData12,
  hatimPageMockData13,
  hatimPageMockData14,
  hatimPageMockData15,
  hatimPageMockData16,
  hatimPageMockData17,
  hatimPageMockData18,
  hatimPageMockData19,
  hatimPageMockData20,
  hatimPageMockData21,
  hatimPageMockData22,
  hatimPageMockData23,
  hatimPageMockData24,
  hatimPageMockData25,
  hatimPageMockData26,
  hatimPageMockData27,
  hatimPageMockData28,
  hatimPageMockData29,
  hatimPageMockData30,
];

final hatimPageMockData1 = [
  {'id': 1, 'status': 'empty'},
  {'id': 2, 'status': 'empty'},
  {'id': 3, 'status': 'empty'},
  {'id': 4, 'status': 'empty'},
  {'id': 5, 'status': 'empty'},
  {'id': 6, 'status': 'process'},
  {'id': 7, 'status': 'process'},
  {'id': 8, 'status': 'process'},
  {'id': 9, 'status': 'process'},
  {'id': 10, 'status': 'process'},
  {'id': 11, 'status': 'process'},
  {'id': 12, 'status': 'process'},
  {'id': 13, 'status': 'process'},
  {'id': 14, 'status': 'done'},
  {'id': 15, 'status': 'done'},
  {'id': 16, 'status': 'done'},
  {'id': 17, 'status': 'done'},
  {'id': 18, 'status': 'done'},
  {'id': 19, 'status': 'done'},
  {'id': 20, 'status': 'done'},
];

final hatimPageMockData2 = [
  {'id': 21, 'status': 'empty'},
  {'id': 22, 'status': 'empty'},
  {'id': 23, 'status': 'empty'},
  {'id': 24, 'status': 'empty'},
  {'id': 25, 'status': 'empty'},
  {'id': 26, 'status': 'process'},
  {'id': 27, 'status': 'process'},
  {'id': 28, 'status': 'process'},
  {'id': 29, 'status': 'process'},
  {'id': 30, 'status': 'process'},
  {'id': 31, 'status': 'process'},
  {'id': 32, 'status': 'process'},
  {'id': 33, 'status': 'process'},
  {'id': 34, 'status': 'done'},
  {'id': 35, 'status': 'done'},
  {'id': 36, 'status': 'done'},
  {'id': 37, 'status': 'done'},
  {'id': 38, 'status': 'done'},
  {'id': 39, 'status': 'done'},
  {'id': 40, 'status': 'done'},
];

final hatimPageMockData3 = [
  {'id': 41, 'status': 'empty'},
  {'id': 42, 'status': 'empty'},
  {'id': 43, 'status': 'empty'},
  {'id': 44, 'status': 'empty'},
  {'id': 45, 'status': 'empty'},
  {'id': 46, 'status': 'process'},
  {'id': 47, 'status': 'process'},
  {'id': 48, 'status': 'process'},
  {'id': 49, 'status': 'process'},
  {'id': 50, 'status': 'process'},
  {'id': 51, 'status': 'process'},
  {'id': 52, 'status': 'process'},
  {'id': 53, 'status': 'process'},
  {'id': 54, 'status': 'done'},
  {'id': 55, 'status': 'done'},
  {'id': 56, 'status': 'done'},
  {'id': 57, 'status': 'done'},
  {'id': 58, 'status': 'done'},
  {'id': 59, 'status': 'done'},
  {'id': 60, 'status': 'done'},
];

final hatimPageMockData4 = [
  {'id': 61, 'status': 'empty'},
  {'id': 62, 'status': 'empty'},
  {'id': 63, 'status': 'empty'},
  {'id': 64, 'status': 'empty'},
  {'id': 65, 'status': 'empty'},
  {'id': 66, 'status': 'process'},
  {'id': 67, 'status': 'process'},
  {'id': 68, 'status': 'process'},
  {'id': 69, 'status': 'process'},
  {'id': 70, 'status': 'process'},
  {'id': 71, 'status': 'process'},
  {'id': 72, 'status': 'process'},
  {'id': 73, 'status': 'process'},
  {'id': 74, 'status': 'done'},
  {'id': 75, 'status': 'done'},
  {'id': 76, 'status': 'done'},
  {'id': 77, 'status': 'done'},
  {'id': 78, 'status': 'done'},
  {'id': 79, 'status': 'done'},
  {'id': 80, 'status': 'done'},
];

final hatimPageMockData5 = [
  {'id': 81, 'status': 'empty'},
  {'id': 82, 'status': 'empty'},
  {'id': 83, 'status': 'empty'},
  {'id': 84, 'status': 'empty'},
  {'id': 85, 'status': 'empty'},
  {'id': 86, 'status': 'process'},
  {'id': 87, 'status': 'process'},
  {'id': 88, 'status': 'process'},
  {'id': 89, 'status': 'process'},
  {'id': 90, 'status': 'process'},
  {'id': 91, 'status': 'process'},
  {'id': 92, 'status': 'process'},
  {'id': 93, 'status': 'process'},
  {'id': 94, 'status': 'done'},
  {'id': 95, 'status': 'done'},
  {'id': 96, 'status': 'done'},
  {'id': 97, 'status': 'done'},
  {'id': 98, 'status': 'done'},
  {'id': 99, 'status': 'done'},
  {'id': 100, 'status': 'done'},
];

final hatimPageMockData6 = [
  {'id': 101, 'status': 'empty'},
  {'id': 102, 'status': 'empty'},
  {'id': 103, 'status': 'empty'},
  {'id': 104, 'status': 'empty'},
  {'id': 105, 'status': 'empty'},
  {'id': 106, 'status': 'process'},
  {'id': 107, 'status': 'process'},
  {'id': 108, 'status': 'process'},
  {'id': 109, 'status': 'process'},
  {'id': 110, 'status': 'process'},
  {'id': 111, 'status': 'process'},
  {'id': 112, 'status': 'process'},
  {'id': 113, 'status': 'process'},
  {'id': 114, 'status': 'done'},
  {'id': 115, 'status': 'done'},
  {'id': 116, 'status': 'done'},
  {'id': 117, 'status': 'done'},
  {'id': 118, 'status': 'done'},
  {'id': 119, 'status': 'done'},
  {'id': 120, 'status': 'done'},
];

final hatimPageMockData7 = [
  {'id': 121, 'status': 'empty'},
  {'id': 122, 'status': 'empty'},
  {'id': 123, 'status': 'empty'},
  {'id': 124, 'status': 'empty'},
  {'id': 125, 'status': 'empty'},
  {'id': 126, 'status': 'process'},
  {'id': 127, 'status': 'process'},
  {'id': 128, 'status': 'process'},
  {'id': 129, 'status': 'process'},
  {'id': 130, 'status': 'process'},
  {'id': 131, 'status': 'process'},
  {'id': 132, 'status': 'process'},
  {'id': 133, 'status': 'process'},
  {'id': 134, 'status': 'done'},
  {'id': 135, 'status': 'done'},
  {'id': 136, 'status': 'done'},
  {'id': 137, 'status': 'done'},
  {'id': 138, 'status': 'done'},
  {'id': 139, 'status': 'done'},
  {'id': 140, 'status': 'done'},
];

final hatimPageMockData8 = [
  {'id': 141, 'status': 'empty'},
  {'id': 142, 'status': 'empty'},
  {'id': 143, 'status': 'empty'},
  {'id': 144, 'status': 'empty'},
  {'id': 145, 'status': 'empty'},
  {'id': 146, 'status': 'process'},
  {'id': 147, 'status': 'process'},
  {'id': 148, 'status': 'process'},
  {'id': 149, 'status': 'process'},
  {'id': 150, 'status': 'process'},
  {'id': 151, 'status': 'process'},
  {'id': 152, 'status': 'process'},
  {'id': 153, 'status': 'process'},
  {'id': 154, 'status': 'done'},
  {'id': 155, 'status': 'done'},
  {'id': 156, 'status': 'done'},
  {'id': 157, 'status': 'done'},
  {'id': 158, 'status': 'done'},
  {'id': 159, 'status': 'done'},
  {'id': 160, 'status': 'done'},
];

final hatimPageMockData9 = [
  {'id': 161, 'status': 'empty'},
  {'id': 162, 'status': 'empty'},
  {'id': 163, 'status': 'empty'},
  {'id': 164, 'status': 'empty'},
  {'id': 165, 'status': 'empty'},
  {'id': 166, 'status': 'process'},
  {'id': 167, 'status': 'process'},
  {'id': 168, 'status': 'process'},
  {'id': 169, 'status': 'process'},
  {'id': 170, 'status': 'process'},
  {'id': 171, 'status': 'process'},
  {'id': 172, 'status': 'process'},
  {'id': 173, 'status': 'process'},
  {'id': 174, 'status': 'done'},
  {'id': 175, 'status': 'done'},
  {'id': 176, 'status': 'done'},
  {'id': 177, 'status': 'done'},
  {'id': 178, 'status': 'done'},
  {'id': 179, 'status': 'done'},
  {'id': 180, 'status': 'done'},
];

final hatimPageMockData10 = [
  {'id': 181, 'status': 'empty'},
  {'id': 182, 'status': 'empty'},
  {'id': 183, 'status': 'empty'},
  {'id': 184, 'status': 'empty'},
  {'id': 185, 'status': 'empty'},
  {'id': 186, 'status': 'process'},
  {'id': 187, 'status': 'process'},
  {'id': 188, 'status': 'process'},
  {'id': 189, 'status': 'process'},
  {'id': 190, 'status': 'process'},
  {'id': 191, 'status': 'process'},
  {'id': 192, 'status': 'process'},
  {'id': 193, 'status': 'process'},
  {'id': 194, 'status': 'done'},
  {'id': 195, 'status': 'done'},
  {'id': 196, 'status': 'done'},
  {'id': 197, 'status': 'done'},
  {'id': 198, 'status': 'done'},
  {'id': 199, 'status': 'done'},
  {'id': 200, 'status': 'done'},
];

final hatimPageMockData11 = [
  {'id': 201, 'status': 'empty'},
  {'id': 202, 'status': 'empty'},
  {'id': 203, 'status': 'empty'},
  {'id': 204, 'status': 'empty'},
  {'id': 205, 'status': 'empty'},
  {'id': 206, 'status': 'process'},
  {'id': 207, 'status': 'process'},
  {'id': 208, 'status': 'process'},
  {'id': 209, 'status': 'process'},
  {'id': 210, 'status': 'process'},
  {'id': 211, 'status': 'process'},
  {'id': 212, 'status': 'process'},
  {'id': 213, 'status': 'process'},
  {'id': 214, 'status': 'done'},
  {'id': 215, 'status': 'done'},
  {'id': 216, 'status': 'done'},
  {'id': 217, 'status': 'done'},
  {'id': 218, 'status': 'done'},
  {'id': 219, 'status': 'done'},
  {'id': 220, 'status': 'done'},
];

final hatimPageMockData12 = [
  {'id': 221, 'status': 'empty'},
  {'id': 222, 'status': 'empty'},
  {'id': 223, 'status': 'empty'},
  {'id': 224, 'status': 'empty'},
  {'id': 225, 'status': 'empty'},
  {'id': 226, 'status': 'process'},
  {'id': 227, 'status': 'process'},
  {'id': 228, 'status': 'process'},
  {'id': 229, 'status': 'process'},
  {'id': 230, 'status': 'process'},
  {'id': 231, 'status': 'process'},
  {'id': 232, 'status': 'process'},
  {'id': 233, 'status': 'process'},
  {'id': 234, 'status': 'done'},
  {'id': 235, 'status': 'done'},
  {'id': 236, 'status': 'done'},
  {'id': 237, 'status': 'done'},
  {'id': 238, 'status': 'done'},
  {'id': 239, 'status': 'done'},
  {'id': 240, 'status': 'done'},
];

final hatimPageMockData13 = [
  {'id': 241, 'status': 'empty'},
  {'id': 242, 'status': 'empty'},
  {'id': 243, 'status': 'empty'},
  {'id': 244, 'status': 'empty'},
  {'id': 245, 'status': 'empty'},
  {'id': 246, 'status': 'process'},
  {'id': 247, 'status': 'process'},
  {'id': 248, 'status': 'process'},
  {'id': 249, 'status': 'process'},
  {'id': 250, 'status': 'process'},
  {'id': 251, 'status': 'process'},
  {'id': 252, 'status': 'process'},
  {'id': 253, 'status': 'process'},
  {'id': 254, 'status': 'done'},
  {'id': 255, 'status': 'done'},
  {'id': 256, 'status': 'done'},
  {'id': 257, 'status': 'done'},
  {'id': 258, 'status': 'done'},
  {'id': 259, 'status': 'done'},
  {'id': 260, 'status': 'done'},
];

final hatimPageMockData14 = [
  {'id': 261, 'status': 'empty'},
  {'id': 262, 'status': 'empty'},
  {'id': 263, 'status': 'empty'},
  {'id': 264, 'status': 'empty'},
  {'id': 265, 'status': 'empty'},
  {'id': 266, 'status': 'process'},
  {'id': 267, 'status': 'process'},
  {'id': 268, 'status': 'process'},
  {'id': 269, 'status': 'process'},
  {'id': 270, 'status': 'process'},
  {'id': 271, 'status': 'process'},
  {'id': 272, 'status': 'process'},
  {'id': 273, 'status': 'process'},
  {'id': 274, 'status': 'done'},
  {'id': 275, 'status': 'done'},
  {'id': 276, 'status': 'done'},
  {'id': 277, 'status': 'done'},
  {'id': 278, 'status': 'done'},
  {'id': 279, 'status': 'done'},
  {'id': 280, 'status': 'done'},
];

final hatimPageMockData15 = [
  {'id': 281, 'status': 'empty'},
  {'id': 282, 'status': 'empty'},
  {'id': 283, 'status': 'empty'},
  {'id': 284, 'status': 'empty'},
  {'id': 285, 'status': 'empty'},
  {'id': 286, 'status': 'process'},
  {'id': 287, 'status': 'process'},
  {'id': 288, 'status': 'process'},
  {'id': 289, 'status': 'process'},
  {'id': 290, 'status': 'process'},
  {'id': 291, 'status': 'process'},
  {'id': 292, 'status': 'process'},
  {'id': 293, 'status': 'process'},
  {'id': 294, 'status': 'done'},
  {'id': 295, 'status': 'done'},
  {'id': 296, 'status': 'done'},
  {'id': 297, 'status': 'done'},
  {'id': 298, 'status': 'done'},
  {'id': 299, 'status': 'done'},
  {'id': 300, 'status': 'done'},
];

final hatimPageMockData16 = [
  {'id': 301, 'status': 'empty'},
  {'id': 302, 'status': 'empty'},
  {'id': 303, 'status': 'empty'},
  {'id': 304, 'status': 'empty'},
  {'id': 305, 'status': 'empty'},
  {'id': 306, 'status': 'process'},
  {'id': 307, 'status': 'process'},
  {'id': 308, 'status': 'process'},
  {'id': 309, 'status': 'process'},
  {'id': 310, 'status': 'process'},
  {'id': 311, 'status': 'process'},
  {'id': 312, 'status': 'process'},
  {'id': 313, 'status': 'process'},
  {'id': 314, 'status': 'done'},
  {'id': 315, 'status': 'done'},
  {'id': 316, 'status': 'done'},
  {'id': 317, 'status': 'done'},
  {'id': 318, 'status': 'done'},
  {'id': 319, 'status': 'done'},
  {'id': 320, 'status': 'done'},
];

final hatimPageMockData17 = [
  {'id': 321, 'status': 'empty'},
  {'id': 322, 'status': 'empty'},
  {'id': 323, 'status': 'empty'},
  {'id': 324, 'status': 'empty'},
  {'id': 325, 'status': 'empty'},
  {'id': 326, 'status': 'process'},
  {'id': 327, 'status': 'process'},
  {'id': 328, 'status': 'process'},
  {'id': 329, 'status': 'process'},
  {'id': 330, 'status': 'process'},
  {'id': 331, 'status': 'process'},
  {'id': 332, 'status': 'process'},
  {'id': 333, 'status': 'process'},
  {'id': 334, 'status': 'done'},
  {'id': 335, 'status': 'done'},
  {'id': 336, 'status': 'done'},
  {'id': 337, 'status': 'done'},
  {'id': 338, 'status': 'done'},
  {'id': 339, 'status': 'done'},
  {'id': 340, 'status': 'done'},
];

final hatimPageMockData18 = [
  {'id': 341, 'status': 'empty'},
  {'id': 342, 'status': 'empty'},
  {'id': 343, 'status': 'empty'},
  {'id': 344, 'status': 'empty'},
  {'id': 345, 'status': 'empty'},
  {'id': 346, 'status': 'process'},
  {'id': 347, 'status': 'process'},
  {'id': 348, 'status': 'process'},
  {'id': 349, 'status': 'process'},
  {'id': 350, 'status': 'process'},
  {'id': 351, 'status': 'process'},
  {'id': 352, 'status': 'process'},
  {'id': 353, 'status': 'process'},
  {'id': 354, 'status': 'done'},
  {'id': 355, 'status': 'done'},
  {'id': 356, 'status': 'done'},
  {'id': 357, 'status': 'done'},
  {'id': 358, 'status': 'done'},
  {'id': 359, 'status': 'done'},
  {'id': 360, 'status': 'done'},
];

final hatimPageMockData19 = [
  {'id': 361, 'status': 'empty'},
  {'id': 362, 'status': 'empty'},
  {'id': 363, 'status': 'empty'},
  {'id': 364, 'status': 'empty'},
  {'id': 365, 'status': 'empty'},
  {'id': 366, 'status': 'process'},
  {'id': 367, 'status': 'process'},
  {'id': 368, 'status': 'process'},
  {'id': 369, 'status': 'process'},
  {'id': 370, 'status': 'process'},
  {'id': 371, 'status': 'process'},
  {'id': 372, 'status': 'process'},
  {'id': 373, 'status': 'process'},
  {'id': 374, 'status': 'done'},
  {'id': 375, 'status': 'done'},
  {'id': 376, 'status': 'done'},
  {'id': 377, 'status': 'done'},
  {'id': 378, 'status': 'done'},
  {'id': 379, 'status': 'done'},
  {'id': 380, 'status': 'done'},
];

final hatimPageMockData20 = [
  {'id': 381, 'status': 'empty'},
  {'id': 382, 'status': 'empty'},
  {'id': 383, 'status': 'empty'},
  {'id': 384, 'status': 'empty'},
  {'id': 385, 'status': 'empty'},
  {'id': 386, 'status': 'process'},
  {'id': 387, 'status': 'process'},
  {'id': 388, 'status': 'process'},
  {'id': 389, 'status': 'process'},
  {'id': 390, 'status': 'process'},
  {'id': 391, 'status': 'process'},
  {'id': 392, 'status': 'process'},
  {'id': 393, 'status': 'process'},
  {'id': 394, 'status': 'done'},
  {'id': 395, 'status': 'done'},
  {'id': 396, 'status': 'done'},
  {'id': 397, 'status': 'done'},
  {'id': 398, 'status': 'done'},
  {'id': 399, 'status': 'done'},
  {'id': 400, 'status': 'done'},
];

final hatimPageMockData21 = [
  {'id': 401, 'status': 'empty'},
  {'id': 402, 'status': 'empty'},
  {'id': 403, 'status': 'empty'},
  {'id': 404, 'status': 'empty'},
  {'id': 405, 'status': 'empty'},
  {'id': 406, 'status': 'process'},
  {'id': 407, 'status': 'process'},
  {'id': 408, 'status': 'process'},
  {'id': 409, 'status': 'process'},
  {'id': 410, 'status': 'process'},
  {'id': 411, 'status': 'process'},
  {'id': 412, 'status': 'process'},
  {'id': 413, 'status': 'process'},
  {'id': 414, 'status': 'done'},
  {'id': 415, 'status': 'done'},
  {'id': 416, 'status': 'done'},
  {'id': 417, 'status': 'done'},
  {'id': 418, 'status': 'done'},
  {'id': 419, 'status': 'done'},
  {'id': 420, 'status': 'done'},
];

final hatimPageMockData22 = [
  {'id': 421, 'status': 'empty'},
  {'id': 422, 'status': 'empty'},
  {'id': 423, 'status': 'empty'},
  {'id': 424, 'status': 'empty'},
  {'id': 425, 'status': 'empty'},
  {'id': 426, 'status': 'process'},
  {'id': 427, 'status': 'process'},
  {'id': 428, 'status': 'process'},
  {'id': 429, 'status': 'process'},
  {'id': 430, 'status': 'process'},
  {'id': 431, 'status': 'process'},
  {'id': 432, 'status': 'process'},
  {'id': 433, 'status': 'process'},
  {'id': 434, 'status': 'done'},
  {'id': 435, 'status': 'done'},
  {'id': 436, 'status': 'done'},
  {'id': 437, 'status': 'done'},
  {'id': 438, 'status': 'done'},
  {'id': 439, 'status': 'done'},
  {'id': 440, 'status': 'done'},
];

final hatimPageMockData23 = [
  {'id': 441, 'status': 'empty'},
  {'id': 442, 'status': 'empty'},
  {'id': 443, 'status': 'empty'},
  {'id': 444, 'status': 'empty'},
  {'id': 445, 'status': 'empty'},
  {'id': 446, 'status': 'process'},
  {'id': 447, 'status': 'process'},
  {'id': 448, 'status': 'process'},
  {'id': 449, 'status': 'process'},
  {'id': 450, 'status': 'process'},
  {'id': 451, 'status': 'process'},
  {'id': 452, 'status': 'process'},
  {'id': 453, 'status': 'process'},
  {'id': 454, 'status': 'done'},
  {'id': 455, 'status': 'done'},
  {'id': 456, 'status': 'done'},
  {'id': 457, 'status': 'done'},
  {'id': 458, 'status': 'done'},
  {'id': 459, 'status': 'done'},
  {'id': 460, 'status': 'done'},
];

final hatimPageMockData24 = [
  {'id': 461, 'status': 'empty'},
  {'id': 462, 'status': 'empty'},
  {'id': 463, 'status': 'empty'},
  {'id': 464, 'status': 'empty'},
  {'id': 465, 'status': 'empty'},
  {'id': 466, 'status': 'process'},
  {'id': 467, 'status': 'process'},
  {'id': 468, 'status': 'process'},
  {'id': 469, 'status': 'process'},
  {'id': 470, 'status': 'process'},
  {'id': 471, 'status': 'process'},
  {'id': 472, 'status': 'process'},
  {'id': 473, 'status': 'process'},
  {'id': 474, 'status': 'done'},
  {'id': 475, 'status': 'done'},
  {'id': 476, 'status': 'done'},
  {'id': 477, 'status': 'done'},
  {'id': 478, 'status': 'done'},
  {'id': 479, 'status': 'done'},
  {'id': 480, 'status': 'done'},
];

final hatimPageMockData25 = [
  {'id': 481, 'status': 'empty'},
  {'id': 482, 'status': 'empty'},
  {'id': 483, 'status': 'empty'},
  {'id': 484, 'status': 'empty'},
  {'id': 485, 'status': 'empty'},
  {'id': 486, 'status': 'process'},
  {'id': 487, 'status': 'process'},
  {'id': 488, 'status': 'process'},
  {'id': 489, 'status': 'process'},
  {'id': 490, 'status': 'process'},
  {'id': 491, 'status': 'process'},
  {'id': 492, 'status': 'process'},
  {'id': 493, 'status': 'process'},
  {'id': 494, 'status': 'done'},
  {'id': 495, 'status': 'done'},
  {'id': 496, 'status': 'done'},
  {'id': 497, 'status': 'done'},
  {'id': 498, 'status': 'done'},
  {'id': 499, 'status': 'done'},
  {'id': 500, 'status': 'done'},
];

final hatimPageMockData26 = [
  {'id': 501, 'status': 'empty'},
  {'id': 502, 'status': 'empty'},
  {'id': 503, 'status': 'empty'},
  {'id': 504, 'status': 'empty'},
  {'id': 505, 'status': 'empty'},
  {'id': 506, 'status': 'process'},
  {'id': 507, 'status': 'process'},
  {'id': 508, 'status': 'process'},
  {'id': 509, 'status': 'process'},
  {'id': 510, 'status': 'process'},
  {'id': 511, 'status': 'process'},
  {'id': 512, 'status': 'process'},
  {'id': 513, 'status': 'process'},
  {'id': 514, 'status': 'done'},
  {'id': 515, 'status': 'done'},
  {'id': 516, 'status': 'done'},
  {'id': 517, 'status': 'done'},
  {'id': 518, 'status': 'done'},
  {'id': 519, 'status': 'done'},
  {'id': 520, 'status': 'done'},
];

final hatimPageMockData27 = [
  {'id': 521, 'status': 'empty'},
  {'id': 522, 'status': 'empty'},
  {'id': 523, 'status': 'empty'},
  {'id': 524, 'status': 'empty'},
  {'id': 525, 'status': 'empty'},
  {'id': 526, 'status': 'process'},
  {'id': 527, 'status': 'process'},
  {'id': 528, 'status': 'process'},
  {'id': 529, 'status': 'process'},
  {'id': 530, 'status': 'process'},
  {'id': 531, 'status': 'process'},
  {'id': 532, 'status': 'process'},
  {'id': 533, 'status': 'process'},
  {'id': 534, 'status': 'done'},
  {'id': 535, 'status': 'done'},
  {'id': 536, 'status': 'done'},
  {'id': 537, 'status': 'done'},
  {'id': 538, 'status': 'done'},
  {'id': 539, 'status': 'done'},
  {'id': 540, 'status': 'done'},
];

final hatimPageMockData28 = [
  {'id': 541, 'status': 'empty'},
  {'id': 542, 'status': 'empty'},
  {'id': 543, 'status': 'empty'},
  {'id': 544, 'status': 'empty'},
  {'id': 545, 'status': 'empty'},
  {'id': 546, 'status': 'process'},
  {'id': 547, 'status': 'process'},
  {'id': 548, 'status': 'process'},
  {'id': 549, 'status': 'process'},
  {'id': 550, 'status': 'process'},
  {'id': 551, 'status': 'process'},
  {'id': 552, 'status': 'process'},
  {'id': 553, 'status': 'process'},
  {'id': 554, 'status': 'done'},
  {'id': 555, 'status': 'done'},
  {'id': 556, 'status': 'done'},
  {'id': 557, 'status': 'done'},
  {'id': 558, 'status': 'done'},
  {'id': 559, 'status': 'done'},
  {'id': 560, 'status': 'done'},
];

final hatimPageMockData29 = [
  {'id': 561, 'status': 'empty'},
  {'id': 562, 'status': 'empty'},
  {'id': 563, 'status': 'empty'},
  {'id': 564, 'status': 'empty'},
  {'id': 565, 'status': 'empty'},
  {'id': 566, 'status': 'process'},
  {'id': 567, 'status': 'process'},
  {'id': 568, 'status': 'process'},
  {'id': 569, 'status': 'process'},
  {'id': 570, 'status': 'process'},
  {'id': 571, 'status': 'process'},
  {'id': 572, 'status': 'process'},
  {'id': 573, 'status': 'process'},
  {'id': 574, 'status': 'done'},
  {'id': 575, 'status': 'done'},
  {'id': 576, 'status': 'done'},
  {'id': 577, 'status': 'done'},
  {'id': 578, 'status': 'done'},
  {'id': 579, 'status': 'done'},
  {'id': 580, 'status': 'done'},
];

final hatimPageMockData30 = [
  {'id': 581, 'status': 'empty'},
  {'id': 582, 'status': 'empty'},
  {'id': 583, 'status': 'empty'},
  {'id': 584, 'status': 'empty'},
  {'id': 585, 'status': 'empty'},
  {'id': 586, 'status': 'process'},
  {'id': 587, 'status': 'process'},
  {'id': 588, 'status': 'process'},
  {'id': 589, 'status': 'process'},
  {'id': 590, 'status': 'process'},
  {'id': 591, 'status': 'process'},
  {'id': 592, 'status': 'process'},
  {'id': 593, 'status': 'process'},
  {'id': 594, 'status': 'done'},
  {'id': 595, 'status': 'done'},
  {'id': 596, 'status': 'done'},
  {'id': 597, 'status': 'done'},
  {'id': 598, 'status': 'done'},
  {'id': 599, 'status': 'done'},
  {'id': 600, 'status': 'done'},
];
