name: mq_prayer_time
description: My Quran Prayers times packages
version: 0.1.0+1
resolution: workspace
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  intl:
  geocoding:
  geolocator:
  timezone:
  flutter_timezone:
  adhan_dart:

  mq_remote_client:
  mq_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail:
  very_good_analysis:
