export 'home/home.dart';
export 'hatim/hatim.dart';
export 'login/login.dart';
export 'main/main.dart';
export 'quran/quran.dart';
export 'settings/settings.dart';
export 'quran_audio/quran_audio.dart';
export 'dev_mode/dev_mode.dart';
export 'donation/donation.dart';
