name: mq_storage
description: My Quran Storage
version: 0.1.0+1
resolution: workspace
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  # flutter_secure_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis:
  mocktail:
