name: mq_storage
description: My Quran Storage
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.7.0-0 <4.0.0"
  flutter: ^3.32.8

dependencies:
  flutter:
    sdk: flutter
  # flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
  mocktail: ^1.0.4
