name: mq_storage
description: My Quran Storage
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.6

dependencies:
  flutter:
    sdk: flutter
  # flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  mocktail: ^1.0.0
