include: package:very_good_analysis/analysis_options.6.0.0.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    directives_ordering: false
    one_member_abstracts: false

formatter:
  trailing_commas: preserve
