include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    directives_ordering: false
    one_member_abstracts: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "lib/l10n/generated/**"
    - "**/*.freezed.dart"
    - "bin/cache/**"

  errors:
    todo: false
    fixme: false
