name: mq_ci_keys
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=3.8.0-0 <4.0.0"

dev_dependencies:
  very_good_analysis: ^9.0.0
  test: ^1.26.3
