export 'settings/settings.dart';
export 'home/home.dart';
export 'juz/juz.dart';
export 'profile/profile.dart';
export 'read/read.dart';
export 'surah/surah.dart';
export 'login/login.dart';
export 'main/main.dart';
export 'quran/quran.dart';
