# Fastfile
platform :ios do
  desc "Increment the build number"
  lane :increment_version do
    firebase_app_distribution_get_latest_release(
      app: "1:417182149715:ios:f6d207c487b6110e76eaa6",
      auth_token: ENV['FIREBASE_TOKEN']
    )
    increment_build_number({
      build_number: latest_release[:buildVersion].to_i + 1
    })
  end

  desc "Distribute the app"
  lane :distribute do
    # build_ios_app()
    firebase_app_distribution(
      app: "1:417182149715:ios:f6d207c487b6110e76eaa6",
      testers: "my_quran_testers",
      release_notes: "Lots of amazing new features to test out!",
      # auth_token: ENV['FIREBASE_TOKEN']
    )
  end
end
