name: mq_either
description: MyQuran Dart Either
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.7.0-0 <4.0.0"

dependencies:  
  meta: ^1.16.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^7.0.0