name: Build & upload to Firebase Android App Distribution 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:   
  build: 
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter doctor

      - run: dart pub global activate flutterfire_cli

      - name: "Melos Install"
        run: dart pub global activate melos

      - name: "Melos bs"
        run: melos bootstrap

      - name: "Build apk"
        run: melos build-apk

      - name: "Build appbundle"
        run: melos build-appbundle

      - run: ls app/build/app/outputs/flutter-apk

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: my_quran_testers
          file: app/build/app/outputs/flutter-apk/app-release.apk  