name: Build & upload to Firebase IOS App Distribution

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build and Distribute iOS App
    runs-on: macos-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2 

    - name: Install Fastlane
      run: gem install fastlane

    - name: Install dependencies
      run: bundle install 

    - name: Run Fastlane Increment Version
      run: fastlane increment_version
      # env:
      #   FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: Run Fastlane Distribute
      run: fastlane distribute
      # env:
      #   FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}