name: Build & upload to Firebase IOS App Distributio

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter doctor

      - run: dart pub global activate flutterfire_cli

      - name: "Melos Install"
        run: dart pub global activate melos

      - name: "Melos bs"
        run: melos bootstrap

      - name: "Navigate to iOS directory and install CocoaPods"
        run: |
          cd app/ios
          pod install

      - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode.app
        
      - name: Running Xcode version
        run: /usr/bin/xcodebuild -version
   
      - name: Build Cleanup
        run: |
          xcodebuild clean -project GitHubAction.xcodeproj -scheme GitHubAction | xcpretty

      - name: Update settings
        run: fastlane run update_code_signing_settings use_automatic_signing:"true" path:"app/ios/Runner.xcodeproj"
          
      - name: Build Archive
        uses: yukiarrr/ios-build-action@v1.12.0  
        with:
          project-path: app/ios/Runner.xcodeproj
          workspace-path: app/ios/Runner.xcworkspace
          scheme: Runner
          configuration: Release
          p12-key-base64: ${{ secrets.P12_KEY_BASE64 }}
          p12-cer-base64: ${{ secrets.P12_KEY_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: Apple Development  
          team-id: ${{ secrets.TEAM_ID }}
          output-path: myquran.ipa
          

      - name: Saving IPA File
        uses: actions/upload-artifact@v2   
        with:
          name: ipa
          path: build/ios/ipa/*.ipa

