name: CI Android

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration_test_android:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.6"
          channel: stable
          cache: true

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Activate Flutterfire CLI
        run: dart pub global activate flutterfire_cli

      - name: Activate Melos
        run: dart pub global activate melos

      - name: Melos Bootstrap
        run: melos bootstrap

      - name: Run Android integration tests - Emulator Setup
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          disable-animations: true
          emulator-options: "-no-window -no-snapshot -no-audio -no-boot-anim"

      - name: Wait for device to be ready and run tests
        run: |
          echo "Checking if device is fully booted..."

          $ANDROID_HOME/platform-tools/adb wait-for-device

          $ANDROID_HOME/platform-tools/adb shell while [[ -z $($(command -v adb) shell getprop sys.boot_completed | tr -d '\r') ]]; do echo "Waiting for boot..."; sleep 5; done

          echo "Device is ready. Starting melos integration-test..."

          melos integration-test

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-screenshots
          path: ./screenshots/*
