name: CI Android

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration_test_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.5"
          channel: stable

      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle
      - run: flutter doctor -v

      - run: dart pub global activate flutterfire_cli

      - name: "Melos Install"
        run: dart pub global activate melos

      - name: "Melos bs"
        run: melos bootstrap

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          script: melos integration-test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-artifact
          path: ./screenshots/*
