name: CI Android

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration_test_android:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.6"
          channel: stable
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle
      - run: flutter doctor -v

      - name: "Melos Install"
        run: dart pub global activate melos

      - name: "Melos bs"
        run: melos bootstrap

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          script: melos integration-test-app

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-artifact
          path: ./app/screenshots/*
