name: CI Android

on:
  push:
    branches: [main, el/migrate-integration-tests]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  integration_test_android:
    runs-on: macos-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dkotlin.daemon.jvm.options=-Xmx4g"
    if: github.event_name == 'push' || (github.event.pull_request.draft == false)
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.4"
          channel: stable
          cache: true

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: "Set up Java"
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: "Setup Gradle Cache"
        uses: gradle/actions/setup-gradle@v3

      - name: "Add Android SDK tools to PATH"
        run: echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: "Flutter Doctor"
        run: flutter doctor -v

      - name: "Activate Flutterfire CLI"
        run: dart pub global activate flutterfire_cli

      - name: "Activate Melos"
        run: dart pub global activate melos

      - name: "Melos Bootstrap"
        run: melos bootstrap

      - name: "Pre-build APK"
        run: cd app && flutter build apk --debug

      - name: "Run test"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: arm64-v8a
          cores: 2
          ram-size: 2048M
          heap-size: 512M
          emulator-options: -no-snapshot-save -no-window -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            adb shell pm grant com.alee.my_quran android.permission.ACCESS_FINE_LOCATION || true
            adb shell pm grant com.alee.my_quran android.permission.ACCESS_COARSE_LOCATION || true
            melos integration-test
