name: CI Android

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration_test_android:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.6"
          channel: stable
          cache: true

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - run: flutter doctor -v

      - run: dart pub global activate flutterfire_cli

      - name: "Melos Install"
        run: dart pub global activate melos

      - name: "Melos bs"
        run: melos bootstrap

      - name: Run Android integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          emulator-options: "-no-window -no-snapshot -no-audio -no-boot-anim"
          script: melos integration-test

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-screenshots
          path: ./screenshots/*
